import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full relative h-screen border-red-500 overflow-hidden">
      <video
        width="100%"
        height="100%"
        autoPlay
        loop
        muted
        className="absolute inset-0 object-cover"
      >
        <source src="/carr.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      {children}
    </div>
  );
}
