import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full video-background relative h-screen overflow-hidden">
      <video
        src="/carr.mp4"
        autoPlay
        loop
        muted
        className="object-cover w-full h-full"
      >
        Your browser does not support the video tag.
      </video>
      {children}
    </div>
  );
}
