import type { Metadata } from "next";
import Menu from "./Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="flex flex-col border-2 w-full">
            <Menu />
            {children}
        </div>
  );
}
