import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex flex-col justify-between bg-black h-full">
      <Header />
      <div id="cars" className="w-full flex justify-center">
        {children}
      </div>
      <Footer />
    </div>
  );
}
