import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex border-2 border-red-500 flex-col justify-between min-h-screen">
      <Header />
      <div className="w-full flex bg-black justify-center h-full">
        {children}
      </div>
      <Footer />
    </div>
  );
}
